version: 2

jobs:
  build:
    docker:
      - image: circleci/clojure:openjdk-8-lein-2.9.1-node-browsers-legacy
        user: circleci
        environment:
          JVM_OPTS: -Xms1g -Xmx1g
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "project.clj" }}
            - v2-dependencies-
      - run:
          name: Fetch dependencies
          command: lein deps
      - run:
          name: Install karma dependencies
          command: yarn add karma karma-cljs-test karma-chrome-launcher --dev
      - run:
          name: Install karma-cli
          command: sudo yarn global add karma-cli
      - save_cache:
          key: v2-dependencies-{{ checksum "project.clj" }}
          paths:
            - ~/.m2
            - ~/repo/node_modules
      - run:
          name: Test
          command: make test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
